# Generated by Django 4.2.16 on 2024-11-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lessonphonics",
            name="unique_lesson_phonics_entry",
        ),
        migrations.AddConstraint(
            model_name="lessonphonics",
            constraint=models.UniqueConstraint(
                fields=("level", "title", "sentence", "audio_file"),
                name="unique_lesson_phonics_entry",
            ),
        ),
    ]
