# Generated by Django 4.2.16 on 2024-11-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_lessonphonics_unique_lesson_phonics_entry_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lessonconversation",
            name="unique_lesson_conversation_entry",
        ),
        migrations.AddConstraint(
            model_name="lessonconversation",
            constraint=models.UniqueConstraint(
                fields=("level", "title", "sentence", "audio_file"),
                name="unique_lesson_conversation_entry",
            ),
        ),
    ]
