# Generated by Django 4.2.16 on 2024-11-21 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "core",
            "0003_remove_lessonconversation_unique_lesson_conversation_entry_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_id", models.PositiveIntegerField()),
                ("content_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("level", models.PositiveIntegerField()),
                ("last_read_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "lesson_id", "content_type")},
            },
        ),
    ]
