# Generated by Django 4.2.16 on 2024-11-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_readinglog"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglog",
            name="last_read_sentence_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
