# Generated by Django 4.2.16 on 2024-11-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_readinglog_last_read_sentence_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpronunciation",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
