# Generated by Django 4.2.16 on 2024-11-25 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_userpronunciation_processed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpronunciation",
            name="score",
        ),
        migrations.AddField(
            model_name="userpronunciation",
            name="mispronounced_ratio",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpronunciation",
            name="mispronounced_words",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpronunciation",
            name="pause_similarity",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpronunciation",
            name="pitch_similarity",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpronunciation",
            name="rhythm_similarity",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpronunciation",
            name="speed_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpronunciation",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
