# Generated by Django 5.1.3 on 2024-11-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_userpronunciation_processed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonconversation",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lesson_images/"),
        ),
        migrations.AddField(
            model_name="lessonnovel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lesson_images/"),
        ),
        migrations.AddField(
            model_name="lessonphonics",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lesson_images/"),
        ),
    ]
