# Generated by Django 5.1.3 on 2024-11-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_lessonconversation_image_lessonnovel_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonconversation",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="lesson_images/Conversation/"
            ),
        ),
        migrations.AlterField(
            model_name="lessonnovel",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="lesson_images/Novel/"
            ),
        ),
        migrations.AlterField(
            model_name="lessonphonics",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="lesson_images/Phonics/"
            ),
        ),
    ]
