# Generated by Django 4.2.16 on 2024-11-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_userpronunciation_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpronunciation",
            name="audio_file",
            field=models.URLField(max_length=500),
        ),
    ]
