# Generated by Django 4.2.16 on 2024-11-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_userpronunciation_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonconversation",
            name="sentence_kor",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="lessonconversation",
            name="title_kor",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lessonnovel",
            name="sentence_kor",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="lessonnovel",
            name="title_kor",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lessonphonics",
            name="sentence_kor",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="lessonphonics",
            name="title_kor",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="lessonconversation",
            constraint=models.UniqueConstraint(
                fields=("level", "title_kor", "sentence_kor", "audio_file"),
                name="unique_lesson_conversation_entry_kor",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonnovel",
            constraint=models.UniqueConstraint(
                fields=("level", "title_kor", "sentence_kor"),
                name="unique_lesson_novel_entry_kor",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonphonics",
            constraint=models.UniqueConstraint(
                fields=("level", "title_kor", "sentence_kor", "audio_file"),
                name="unique_lesson_phonics_entry_kor",
            ),
        ),
    ]
