# Generated by Django 5.1.3 on 2024-11-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_lessonconversation_image_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lessonconversation",
            name="unique_lesson_conversation_entry",
        ),
        migrations.RemoveConstraint(
            model_name="lessonnovel",
            name="unique_lesson_novel_entry",
        ),
        migrations.RemoveConstraint(
            model_name="lessonphonics",
            name="unique_lesson_phonics_entry",
        ),
        migrations.RemoveField(
            model_name="lessonconversation",
            name="image",
        ),
        migrations.RemoveField(
            model_name="lessonnovel",
            name="image",
        ),
        migrations.RemoveField(
            model_name="lessonphonics",
            name="image",
        ),
        migrations.AddField(
            model_name="lessonconversation",
            name="image_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lessonnovel",
            name="image_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lessonphonics",
            name="image_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
