# Generated by Django 5.1.3 on 2024-11-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0009_remove_lessonconversation_unique_lesson_conversation_entry_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessonconversation",
            old_name="image_filename",
            new_name="image_path",
        ),
        migrations.RenameField(
            model_name="lessonnovel",
            old_name="image_filename",
            new_name="image_path",
        ),
        migrations.RenameField(
            model_name="lessonphonics",
            old_name="image_filename",
            new_name="image_path",
        ),
    ]
