# Generated by Django 5.1.3 on 2024-11-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_rename_image_filename_lessonconversation_image_path_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lessonconversation",
            constraint=models.UniqueConstraint(
                fields=("level", "title", "sentence", "audio_file"),
                name="unique_lesson_conversation_entry",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonnovel",
            constraint=models.UniqueConstraint(
                fields=("level", "title", "sentence"), name="unique_lesson_novel_entry"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonphonics",
            constraint=models.UniqueConstraint(
                fields=("level", "title", "sentence", "audio_file"),
                name="unique_lesson_phonics_entry",
            ),
        ),
    ]
